### ISSUE TITLE
Start / Stop canister

### ISSUE THREAD

**Issue by infu** [hadronous/pic-js#23]
Seems start and stop canister is missing. It would be great for various scenarios - when we want to check how a multi-canister setup will respond when some of the canisters stop.

Would this workaround do it ? Using updateCanisterSettings to put freezing threshold higher than the cycle balance to stop and then moving it down to start?

**Comment by nathanosdev** [comment]
Adding support for stop and start is pretty trivial, I should be able to add it within the next days. If you need it sooner, feel free to make a PR.

**Comment by nathanosdev** [comment]
This is released now in v0.4.0.

Docs:
- [startCanister](https://hadronous.github.io/pic-js/docs/pic-js/classes/PocketIc#startcanister)
- [stopCanister](https://hadronous.github.io/pic-js/docs/pic-js/classes/PocketIc#stopcanister)

Feel free to open a new ticket if you need anything else.
