### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by timohanke** [hadronous/pic-js#27]
Could update these dependencies
```
    "@dfinity/agent": "~0.21.4",
    "@dfinity/candid": "~0.21.4",
    "@dfinity/identity": "~0.21.4",
    "@dfinity/principal": "~0.21.4",
 ```
 so they match the new major version? They are now at 1.0.1

**Comment by nathanosdev** [comment]
Thanks for the ping on this.

Done in https://github.com/hadronous/pic-js/pull/29 and released in v0.5.0.
