### ISSUE TITLE
`declarations` from `dfx generatge`

### ISSUE THREAD

**Issue by baolongt** [hadronous/pic-js#55]
I raise some issue with Jest, TS when try to import `_SERVICE` and `idlFactory` using this import 

```
import { idlFactory, _SERVICE } from "../declarations/backend/";
```

Instead fix the issue I'm try to change the `backend.did.d.ts` to `backend.did.ts` and `backend.did.js` to `backend.ts` then import like this 
```
import { _SERVICE } from "../declarations/backend/backend.did.ts";
import { idlFactory } from "../declarations/backend/backend.ts";
```

The test run successfully but don't know that is a good solution or not. And it required more manually steps

**Comment by baolongt** [comment]
I solved this by adding 
```
   // jest.config.ts
   transform: {
        "^.+\\.[tj]s$": "ts-jest"
    },
```

**Comment by nathanosdev** [comment]
Glad you found a solution
