### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'protocol')

### ISSUE THREAD

**Issue by aliscie** [hadronous/pic-js#58]
27|   const alice = createIdentity("1");
     28|   const pic = await PocketIc.create();
       |                              ^
     29|   const fixture = await pic.setupCanister<_SERVICE>(idlFactory, WASM_PATH);
     30|   fixture.actor.setIdentity(alice);

**Comment by nathanosdev** [comment]
Can you provide a full, but minimal reproduction please?

There is nothing called `protocol` in pic-js, so this is likely third party code.

**Comment by aliscie** [comment]
Hi, sorry for my late response
```tsx
// setup file
import { afterAll, beforeAll, vi } from "vitest";
import "@testing-library/jest-dom/vitest";
import { createIdentity, PocketIc } from "@hadronous/pic";

const setupTestEnvironment = async () => {
  console.log("setupTestEnvironment");
  const alice = createIdentity("1");
  const pic = await PocketIc.create();
  return "newUser";
};

beforeAll(setupTestEnvironment);

afterAll(async () => {
  // await global.pic.tearDown();
  // delete global.lol;
  // delete global.pic;
  // delete global.actor;
  // delete global.loginAs;
  // delete global.user;
});
```

```vitest
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    alias: {
      "@": "/src",
    },
    environment: "jsdom",
    globals: true,
    threads: false,
    watch: true,
    setupFiles: ["./src/frontend/tests/backend/backend_unit_test_setup.ts"],
    setupFilesAfterEnv: [
      "@testing-library/jest-dom/extend-expect",
      // "./src/frontend/tests/React/testSetup.ts",
    ],
  },
});

```

**Comment by nathanosdev** [comment]
You're not providing a `url` to the `PocketIc.create()` method.

Please see the docs on how to setup Vitest to work with pic-js: https://hadronous.github.io/pic-js/docs/guides/using-vitest.
Also see this example project: https://github.com/hadronous/pic-js/tree/main/examples/counter.
And the docs for the `create` method: https://hadronous.github.io/pic-js/docs/pic-js/classes/PocketIc#create.

And please consider using TypeScript which can catch these kinds of mistakes for you.
