### ISSUE TITLE
Update npm published package https://www.npmjs.com/package/pic-ic

### ISSUE THREAD

**Issue by dominicletz** [hadronous/pic-js#69]
Hey there, just saw that the current master does support pocket-ic in newer versions after failing with the pic-ic build from npm. Would you mind updating the npm published release?

Thanks!

**Comment by dominicletz** [comment]
Looking a bit deeper it seems that above npm package is not sourced from here but from https://github.com/ZenVoich/pic-js instead....

**Comment by nathanosdev** [comment]
Yes that's a forked NPM package, so I'll close this ticket. I'd be happy to merge any useful changes from forks.
